### ISSUE TITLE
Сборка в exe

### ISSUE THREAD

**Issue by khorevaa** [oscript-library/gitsync#156]
- [x] модифицировать v8storage (запаковать обработку конвертации MXL-JSON)
     - [x] после тестов выпустить релиз v8storage
- [x] сделать механизм запаковки плагинов как библиотеки
- [ ] описать в readme как собрать со своими плагинами
- [x] добавить заглушку на команды `plugins install` и `plugins usage`
- [x] доработать плагин unpack (сейчас не работает) - использование сторонней утилиты v8unpack https://github.com/khorevaa/gitsync-plugins/issues/9
     - [x] Для сборки в exe отказаться от v8unpack - dll - либы не  умеет корректно подключаться в режиме exe
     - [x] Взять код из vanessa-runner по запуск tool1CD 
     - [x] после тестов выпустить релиз плагина v8unpack
- [x] доработать плагин tool1CD (сейчас не работает) - использование сторонней утилиты tool1CD https://github.com/khorevaa/gitsync-plugins/issues/10
     
     - [x] после тестов выпустить релиз плагина tool1CD (не требуется)
- [x] Не удаляются файлы после работы с v8storage https://github.com/khorevaa/v8storage/issues/8

Собранный прототип от 16.10.2018 [gitsync.zip](https://github.com/oscript-library/gitsync/files/2482903/gitsync.zip)

**Comment by khorevaa** [comment]
Реализовано.
Собранный файл [gitsync.zip](https://github.com/oscript-library/gitsync/files/2956157/gitsync.zip)
